### ISSUE TITLE
[Windows] error at launch

### ISSUE THREAD

**Issue by mess-maker** [dhojayev/traderepublic-portfolio-downloader#16]
Tried also on windows

**Describe the bug**
fail to launch

**Screenshots**
```
> .\portfoliodownloader.exe 

2024/05/18 17:51:14 /github/workspace/internal/database/sqlite.go:24
[error] failed to initialize database, got error Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
May 18 17:51:14.857 [PANI] could not open sqlite db: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
panic: (*logrus.Entry) 0xc00019f650

goroutine 1 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc00019f0a0, 0x0, {0xc0000c1480, 0x73})
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:260 +0x491
github.com/sirupsen/logrus.(*Entry).Log(0xc00019f0a0, 0x0, {0xc0000b9ea0?, 0xefce60?, 0xdd82e0?})
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x48
github.com/sirupsen/logrus.(*Logger).Log(0xc000179080, 0x0, {0xc0000b9ea0, 0x1, 0x1})
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/logger.go:204 +0x58
github.com/sirupsen/logrus.(*Logger).Panic(...)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/logger.go:253
main.main()
        /github/workspace/cmd/portfoliodownloader/public/main.go:33 +0x2b3
````

**Desktop (please complete the following information):**
 - OS: [W11]

**Comment by dhojayev** [comment]
Thanks for the report! I will fix it today. Unfortunately I always use it on macOS and never had a chance to face the issue. 
We definitely need to consider testing executing the bins on all supported OSes. But as said, will fix this shortly today.

**Comment by mess-maker** [comment]
you welcome

vmware Fusion pro is now free for non commercial use, should run windows nicely
https://blogs.vmware.com/workstation/2024/05/vmware-workstation-pro-now-available-free-for-personal-use.html

**Comment by dhojayev** [comment]
Thanks for the hint. I will definitely use it locally to test the app on windows. Unfortunately it does not allow me to run amd64 version of Windows 11 on M1 Mac. But I can deal with that.
The issue will be fixed in the upcoming release.
