### ISSUE TITLE
Implement downloading non-transactional PDF documents, aka "Aktivität"

### ISSUE THREAD

**Issue by dhojayev** [dhojayev/traderepublic-portfolio-downloader#33]
**Is your feature request related to a problem? Please describe.**
We currently only download PDF documents attached to transactions. There are still many other documents that would be great to grab automatically, such as yearly tax report, Vorabpauschale, etc.

**Describe the solution you'd like**
Activity related documents shall be saved in "activity" directory and also be split by months.

**Comment by dhojayev** [comment]
Hey @tenjaa,
I implemented non-transactional documents downloading. Could you maybe test it, that would help a lot as it seems that you have a very rich on data account :)
https://github.com/dhojayev/traderepublic-portfolio-downloader/actions/runs/9538749704

**Comment by dhojayev** [comment]
Hey @martinAtGitHub, maybe you wanna test it as well. Any input could help bughunting. Thanks in advance!

**Comment by dhojayev** [comment]
@dmagur  please check it too

**Comment by dmagur** [comment]
fails on this
`      "action": {
        "payload": {
          "verificationTransfer": false
        },
        "type": "redirectCashAccountScreen"
      },`

**Comment by dhojayev** [comment]
> fails on this ` "action": { "payload": { "verificationTransfer": false }, "type": "redirectCashAccountScreen" },`

Thanks for checking. I just pushed a fix for that. Please download and run it again:
https://github.com/dhojayev/traderepublic-portfolio-downloader/actions/runs/9550191630

**Comment by dhojayev** [comment]
@dmagur has confirmed that it is working now so I will release it.

**Comment by tenjaa** [comment]
@dhojayev I also gave it (latest release where this was merged) a try.
My activity log tells me `skipped: 20` so some seem to be missing, but most of them worked.

Not a problem for me, but if you want to dig deeper just tell me what data you need :)

**Comment by dhojayev** [comment]
> @dhojayev I also gave it (latest release where this was merged) a try.
> 
> My activity log tells me `skipped: 20` so some seem to be missing, but most of them worked.
> 
> 
> 
> Not a problem for me, but if you want to dig deeper just tell me what data you need :)

Hey @tenjaa!
Thanks for your reply. 
Skipped entries are expected since not all activity entries in your account have documents and we ignore those entities. But I am happy to hear that it worked without any errors on your end.
