### ISSUE TITLE
Unable to fetch timeline details

### ISSUE THREAD

**Issue by ToSa27** [dhojayev/traderepublic-portfolio-downloader#39]
It looks like TR changed something server side as all tools I looked at currently fail with the following error message:
{"errors":[{"errorCode":"UNKNOWN_ERROR","errorField":null,"errorMessage":"Unknown error","meta":{"source":"PLATFORM"}}]}
when trying to download the timeline. More specific this is the first received message after the "connected" message when subscribing to the timeline.

**To Reproduce**
just run and watch the logs for the error

**Desktop (please complete the following information):**
 - OS: Windows
 - Windows Terminal

**Comment by dhojayev** [comment]
Hey @ToSa27!
I tested now and I get no errors. 
It seems that you have a response that is not expected by any of the tools you've tried so far. 
Could you post the console output here? But please make sure to remove any private information like the phone number, etc.

**Comment by dhojayev** [comment]
Hey @ToSa27,
Do you still face the issue? If not - I will close the issue

**Comment by ToSa27** [comment]
I can't reproduce the error message anymore using the same executable - so maybe it was a glitch on the TradeRepublic server side. I still have the logs with the error but probably not worth digging into it as it does not happen anymore.
