### ISSUE TITLE
Incorrect portfolio value

### ISSUE THREAD

**Issue by dhojayev** [dhojayev/traderepublic-portfolio-downloader#7]
Incorrect value is recorded with sale transaction. Portfolio value is being deducted with the profit/loss which leads to incorrect value. Portfolio value shall be calculated by excluding profit/gain from it.

**Comment by dhojayev** [comment]
@dmagur I propose to get rid of this value completely for now as it requires complete revamp of calculation in order to achieve correct values: we need to take into account all commissions that were paid when purchasing an asset and deduct them in order to find out invested amount in the first place.
Plus, I think it would be good to display only the values provided by TR for now and once we are ready introduce new values which we calculate and add an info into readme that these values are for reference only and we do not guarantee correct values.

**Comment by dmagur** [comment]
@dhojayev ok, I think you are right, let's concentrate on the values calculated by TR first

**Comment by dhojayev** [comment]
Bug has been addressed by removing the value completely for now. New implementation is in progress
